### ISSUE TITLE
When creating an isolate in iOS, the appLovin does not send any callback

### ISSUE THREAD

**Issue by jhlee-danbi** [AppLovin/AppLovin-MAX-Flutter#156]
### MAX Plugin Version

3.3.0

### Flutter Version

3.10.6

### Device/Platform Info

iOS

### Current Behavior

I'm a beginner developer, so my explanation might be lacking, but I'll try to describe my situation as detailed as possible.

I am using the [flutter_background_service](https://github.com/ekasetiawans/flutter_background_service) package. In iOS foregound, this package creates a new isolate in Dart and maintains continuous communication with the iOS native code.

Please refer to the code below.
https://github.com/ekasetiawans/flutter_background_service/blob/43e64b3a3b5772b7844c5bc5d98c4f9aaba4a054/packages/flutter_background_service_ios/lib/flutter_background_service_ios.dart#L69C5-L72C81

When using this package, the appLovin does not send any callback. => `setRewardedAdListener` is not working!
However, when not using this package, the AppLovin ad callbacks work fine!

We are looking for a solution to this issue, but it remains unresolved despite our waiting. (#56)

Consequently, we have no choice but to add a delay to show the AppLovin ads...

```dart
Future<void> _appLovinRewardedAdLoadOnIOS() async {
    AppLovinMAX.loadRewardedAd(_applovinRewardedUnitId);

    await Future.delayed(const Duration(seconds: 3), () async {  // added a delay to show the AppLovin ad
      final adReady = await AppLovinMAX.isRewardedAdReady(_applovinRewardedUnitId) ?? false;
      if (!adReady) {
        return;
      }

      AppLovinMAX.showRewardedAd(_applovinRewardedUnitId); 

      await Future.delayed(const Duration(seconds: 15), () { // added delay to provide rewards to users
        onAdCompleted();
      });
    });
  }
```

I feel that this is not an ideal implementation and I need help. I would like to resolve this issue.

### Expected Behavior

I hope that `setRewardedAdListener` method properly.

### How to Reproduce

1. init and run background service( https://pub.dev/packages/flutter_background_service/example)
2. init AppLovin SDK
3. load rewarded AD
4. Watch the callback is coming

**Comment by alhiwatan** [comment]
@jhlee-danbi, we are able to reproduce the issue on our end.   To identify where the issue is located, we created a sample program that sends an integer every second from the iOS Flutter plugin.   The program is based on the `flutter_background_service` example and does not contain our `AppLovinMAX` package.   

First, we verified that the program works without flutter_background_service.   The program does not work with `flutter_background_service`.   The iOS Flutter plugin keeps sending an integer.

Please file the issue to the flutter_background_service side.
