### ISSUE TITLE
Can't remove or update AppLovinMediationYandexAdapter

### ISSUE THREAD

**Issue by kreativityapps** [AppLovin/AppLovin-MAX-Flutter#272]
### MAX Plugin Version

4.0.2

### Flutter Version

3.24.4

### Device/Platform Info

ios

### Current Behavior

On ios in the Podfile I had `pod 'AppLovinMediationYandexAdapter', '5.9.1.0'`.
Updated without issues until `pod 'AppLovinMediationYandexAdapter', '6.0.0.0'`, but trying to update to 6.1.0.0 or later causes a crash on iOS on start-up only with a black screen, without splashscreen:
`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)` inside GeneratedPluginRegistrant `(void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry` at `GeneratedPluginRegistrant.register(with: self)`

Even only trying to remove `AppLovinMediationYandexAdapter` causes the same crash.

Between changes I cleaned up the pods and reinstalled them, deintegrate, remove pods directory, cache clean, repo update and install, it didn't help.

### How to Reproduce

In the demo app I can't reproduce the same crash.

### Reproducible in the demo app?

No

**Comment by alhiwatan** [comment]
@kreativityapps, Yandex has its own dependencies and installs additional packages. Could you check if your app is compatible with these packages? Since this issue isn’t reproducible with our demo app, our SDK doesn’t depend on any Yandex SDK components without the `AppLovinMediationYandexAdapter`. Also, we've released a new version, 7.5.0.3, of the `AppLovinMediationYandexAdapter`.
